theme: jekyll-theme-cayman
title: BirdNET Analyzer
show_downloads: true
github:
  zip_url: https://tuc.cloud/index.php/s/myHcJNsDsMrDqMM/download/BirdNET-Analyzer.zip
#description: BirdNET Analyzer documentation.
