name: Organize Manila Files

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  organize_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # - name: Install Dependencies
      #   run: pip install -r requirements.txt  # If you add dependencies later

      - name: SSH into Jetstream2 and Run Script
        env:
          SSH_KEY: ${{ secrets.JETSTREAM2_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@149.165.174.37 \
            "source /home/ubuntu/streamlit-venv/bin/activate && \
             python3 /home/ubuntu/EcoAcousticAI/move_manila_files.py"
