name: Shut Down Instance

on:
  schedule:
    # Runs every Tuesday at 08:00 AM UTC
    - cron: '0 8 * * 2'
  workflow_dispatch: # Allow manual triggering if needed

jobs:
  shelve-instance:
    runs-on: ubuntu-latest
    steps:
        - name: Install OpenStack CLI
          run: sudo apt update && sudo apt install -y python3-openstackclient
        - name: Authenticate with OpenStack
          run: |
            mkdir -p ~/.config/openstack
                      echo "${{ secrets.CLOUDS_YAML }}" > ~/.config/openstack/clouds.yaml
                      chmod 600 ~/.config/openstack/clouds.yaml
                      openstack --os-cloud=BIO230143_IU server list  # Debug check

        - name: Remove New Directories
          run: |
            SSH_KEY=$HOME/.ssh/jetstream2_key
            ssh -o StrictHostKeyChecking=no -i "$SSH_KEY" ubuntu@149.165.170.20 << EOF
            
            sudo umount /tmp/osn_bucket/ubna_data_01
            sudo umount /tmp/osn_bucket/ubna_data_02
            sudo umount /tmp/osn_bucket/ubna_data_03
            sudo umount /tmp/osn_bucket/ubna_data_04
            sudo umount /tmp/osn_bucket/ubna_data_04

        - name: Shelve Instance
          run: |
                      INSTANCE_ID="2e41f703-6464-499f-8faf-6412fcfcd8cc"
                      STATUS=$(openstack --os-cloud=BIO230143_IU server show $INSTANCE_ID -f value -c status)
            
                      echo "Checking if instance is ready to be shelved..."
                      while [[ "$STATUS" == "BUILD" || "$STATUS" == "REBOOT" || "$STATUS" == "UNSHELVING" ]]; do
                        echo "Instance is still transitioning. Waiting 60 seconds..."
                        sleep 60
                        STATUS=$(openstack --os-cloud=BIO230143_IU server show $INSTANCE_ID -f value -c status)
                      done
            
                      if [[ "$STATUS" == "ACTIVE" ]]; then
                        echo "Shelving instance now..."
                        openstack --os-cloud=BIO230143_IU server shelve $INSTANCE_ID
                      else
                        echo "Instance is not in a valid state for shelving. Current status: $STATUS"
                      fi
