name: Sync Selected Files from BattyBirdNET-Analyzer

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync-and-copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout EcoAcousticAI repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure clean clone in a temporary directory
        run: |
          rm -rf /tmp/battybirdnet_clone  # Remove only the temporary clone folder
          git clone https://github.com/jacobp24/BattyBirdNET-Analyzer.git /tmp/battybirdnet_clone
          cd /tmp/battybirdnet_clone
          git remote add upstream https://github.com/rdz-oss/BattyBirdNET-Analyzer.git
          git fetch upstream
          git merge upstream/main
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jacobp24/BattyBirdNET-Analyzer.git main

      - name: Copy selected files and folders
        run: |
          mkdir -p BattyBirdNET-Analyzer
          cp -r /tmp/battybirdnet_clone/checkpoints BattyBirdNET-Analyzer/
          cp -r /tmp/battybirdnet_clone/labels BattyBirdNET-Analyzer/
          cp -r /tmp/battybirdnet_clone/put-your-files-here BattyBirdNET-Analyzer/
          cp /tmp/battybirdnet_clone/audio.py BattyBirdNET-Analyzer/
          cp /tmp/battybirdnet_clone/bat_ident.py BattyBirdNET-Analyzer/
          cp /tmp/battybirdnet_clone/config.py BattyBirdNET-Analyzer/
          cp /tmp/battybirdnet_clone/model.py BattyBirdNET-Analyzer/
          cp /tmp/battybirdnet_clone/species.py BattyBirdNET-Analyzer/
          cp /tmp/battybirdnet_clone/utils.py BattyBirdNET-Analyzer/

      - name: Set Git user info
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add BattyBirdNET-Analyzer/
          git commit -m "Automated sync of selected files from BattyBirdNET-Analyzer" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

