name: Model Run Part 2 (Resume)

on:
  workflow_run:
    workflows: ["Model Run to Manila Mount"]  # Name of the first workflow
    types:
      - completed
  workflow_dispatch:  # Allows manual trigger

jobs:
  resume-docker:
    runs-on: ubuntu-latest
    if: always()
    steps:

      - name: Set up SSH Key for Remote Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.JETSTREAM2_SSH_KEY }}" > ~/.ssh/jetstream2_key
          chmod 600 ~/.ssh/jetstream2_key
          ssh-keyscan -H "149.165.170.20" >> ~/.ssh/known_hosts

      - name: Resume Model Run
        run: |
            SSH_KEY=$HOME/.ssh/jetstream2_key
            ssh -o StrictHostKeyChecking=no -i "$SSH_KEY" ubuntu@149.165.170.20 << EOF
              cd /home/ubuntu/EcoAcousticAI/
  
              echo "Contents of new_directories.txt:"
              cat new_directories.txt
              echo "----------------------"

              chmod +x run_docker_part2.sh
              ./run_docker_part2.sh